version: '2'

services:

  server:
    image: postgres:9.5.12-alpine
    expose:
      - '5432'

  client:
    image: mrcschwering/psql-client:latest
    depends_on:
        - server

  app:
    image: mrcschwering/cci-findata_build:latest
    environment:
        - ALPHAVANTAGE_API_KEY
    depends_on:
        - server
