version: 2
jobs:

  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build finData
          command: docker build -t "mrcschwering/cci-findata_build:latest" .
      - run:
          name: Push finData build
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_build:latest"

  smoke-scraper:
    working_directory: /app
    docker:
      - image: mrcschwering/cci-findata_build:latest
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_scrape*"

  smoke-loader:
    working_directory: /app
    docker:
      - image: mrcschwering/cci-findata_build:latest
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_load*"

  integration-postgres:
    docker:
      - image: mrcschwering/docker-compose:18.03.0-ce-git
    environment:
      PG_NAME: "postgres_server"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start server and client containers
          command: |
            docker-compose up -d
            docker-compose ps
            docker network ls
            docker inspect project_client_1
            docker inspect project_server_1
      - run:
          name: Create a new DB
          command: |
            docker-compose run client \
              createdb -h server -p 5432 findata -U postgres -w postgres
      - run:
          name: Query new DB
          command: |
            docker-compose run client \
              psql -h server -p 5432 findata -U postgres -w postgres \
              --command="\l"

  deploy:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build tested finData
          command: docker build -t "mrcschwering/cci-findata_deploy:latest" .
      - run:
          name: Push tested finData
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_deploy:latest"

workflows:
  version: 2
  build_and_test:
    jobs:
      - integration-postgres
      - build:
          requires:
            - integration-postgres
      - smoke-scraper:
          requires:
            - build
      - smoke-loader:
          requires:
            - build
      - deploy:
          requires:
            - smoke-scraper
            - smoke-loader
