version: 1
jobs:
  build:
    docker:
      - image: python:2.7-slim
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: echo $PATH
      - run: python test.py
workflows:
  version: 1
  build:
    jobs:
      - build
