version: 2
jobs:

  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build finData
          command: docker build -t "mrcschwering/cci-findata_build:latest" .
      - run:
          name: Push finData build
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_build:latest"

  smoke-scraper:
    working_directory: /app
    docker:
      - image: mrcschwering/cci-findata_build:latest
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_scrape*"

  smoke-loader:
    working_directory: /app
    docker:
      - image: mrcschwering/cci-findata_build:latest
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_load*"

  integration-tests:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            apk --update add py2-pip
            pip install docker-compose
            docker-compose --version
      - run:
          name: Start Container
          command: |
            docker-compose up -d
            sleep 5
            docker-compose ps
      - run:
          name: Create DB using psql client
          command: |
            docker-compose run client "CREATE DATABASE findata;"
            docker-compose run client "\l"
      - run:
          name: Check DB using app
          command: |
            python3 -m finData.scrape

  deploy:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build tested finData
          command: docker build -t "mrcschwering/cci-findata_deploy:latest" .
      - run:
          name: Push tested finData
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_deploy:latest"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - smoke-scraper:
          requires:
            - build
      - smoke-loader:
          requires:
            - build
      - integration-tests:
          requires:
            - smoke-scraper
            - smoke-loader
      - deploy:
          requires:
            - integration-tests
