version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - run:
          name: Create workspace
          command: mkdir /persist_job
      - run:
          name: See build job
          command: ls -la && ls -la /
      - run:
          name: Install Dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
  unittest-scraper:
    docker:
      - image: python:3.5-slim
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: python -m unittest discover -s test -v
  unittest-dbConnector:
    docker:
      - image: python:3.5-slim
    steps:
      - checkout
      - run: pip3 install -r requirements.txt
      - run: echo "Hi"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unittest-scraper:
          requires:
            - build
      - unittest-dbConnector:
          requires:
            - build
