version: 1
jobs:
  build:
    docker:
      - image: python:2.7-slim
    steps:
      - checkout
      - run: apt-get install libxml2-dev libxslt1-dev python-dev
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s test -v
workflows:
  version: 1
  build:
    jobs:
      - build
