version: 2
jobs:

  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build finData
          command: docker build -t "mrcschwering/cci-findata_build:latest" .
      - run:
          name: Push finData build
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_build:latest"

  smoke-scraper:
    working_directory: /app
    docker:
      - image: mrcschwering/cci-findata_build:latest
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_scrape*"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - smoke-scraper:
          requires:
            - build
