version: 2
jobs:

  build:
    environment:
      build: mrcschwering/cci-findata_build:latest
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build finData
          command: docker build -t "$build" .
      - run:
          name: Push finData build
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "mrcschwering/cci-findata_build:latest"

  smoke-scraper:
    docker:
      - image: mrcschwering/cci-findata_build:latest
    working_directory: /app
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_scrape*"

  smoke-loader:
    docker:
      - image: mrcschwering/cci-findata_build:latest
    working_directory: /app
    steps:
      - run: python3 -m unittest discover -s test -v -p "*test_load*"

  integration-tests:
    docker:
      - image: mrcschwering/docker-compose-git:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Container
          command: |
            docker-compose up -d
            sleep 5
            docker-compose ps
      - run:
          name: Create DB using psql client
          command: |
            docker-compose run client "CREATE DATABASE findata;"
            docker-compose run client "\l"
      - run:
          name: Run Integration Tests
          command: |
            docker-compose run app test.integration_test

  deploy:
    environment:
      build: mrcschwering/cci-findata_build:latest
      deploy: "mrcschwering/cci-findata_deploy:latest"
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull and tag tested image
          command: |
            docker pull "$build"
            docker tag "$build" "$deploy"
      - run:
          name: Push tested finData
          command: |
            docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
            docker push "$deploy"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - smoke-scraper:
          requires:
            - build
      - smoke-loader:
          requires:
            - build
      - integration-tests:
          requires:
            - smoke-scraper
            - smoke-loader
      - deploy:
          requires:
            - integration-tests
