version: 1
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s test -v
workflows:
  version: 1
  build:
    jobs:
      - build
