version: '2'

services:

  server:
    image: postgres:9.5.12-alpine
    volumes:
      - findata:/var/lib/postgresql/data

  app:
    image: mrcschwering/cci-findata_deploy:latest
    environment:
        - ALPHAVANTAGE_API_KEY
    depends_on:
        - server


volumes:

  findata:
    external: true
